openapi: 3.0.0
info:
  title: Game Service API
  version: 0.1.0
  description: API for slot games and bet processing

servers:
  - url: http://localhost:8002
    description: Local development server

paths:
  /:
    get:
      summary: Service root
      responses:
        '200':
          description: Service information
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                  status:
                    type: string

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /games/:
    get:
      summary: List available games
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string

  /games/{game_id}/bet:
    post:
      summary: Place a bet on a game
      parameters:
        - name: game_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                player_id:
                  type: integer
                amount:
                  type: number
                  format: float
              required:
                - player_id
                - amount
      responses:
        '200':
          description: Bet result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BetResult'

components:
  schemas:
    BetResult:
      type: object
      properties:
        player_id:
          type: integer
        game_id:
          type: string
        bet_amount:
          type: number
          format: float
        result:
          type: string
          enum: [win, lose, pending]
        win_amount:
          type: number
          format: float
